Test deleting add-ons
nvaccess/addon-datastore pull request #4232
Opened 2024-09-06 04:01 UTC by seanbudd

2024-09-06 04:07 UTC, seanbudd commented on .github/workflows/validateAllAddons.yml
> +    - name: Install addon download validation dependencies
this should probably be moved further up - e.g. below creating validation errors file

2024-09-06 06:33 UTC, SaschaCowley requested changes

2024-09-06 06:33 UTC, SaschaCowley commented on .github/workflows/checkAddonUrlAndHash.js
> +  files.forEach(file => {
Can these be renamed to something slightly more descriptive please?
```suggestion
  const metadataFiles = glob.globSync(globPattern);
  metadataFiles.forEach(metadataFile => {
```

2024-09-06 06:33 UTC, SaschaCowley commented on .github/workflows/checkAddonUrlAndHash.js
I think this looks good. I have to admit the deeply nested anonymous functions are a little difficult to read. Could you perhaps either refactor them to be separate functions, or add more comments to better signpost?

2024-09-06 06:36 UTC, SaschaCowley commented
Also, could the the generated PR be made to include the reason each metadata file is being deleted? Off the top of my head, you could do this by echoing the reason for deletion to a temp file in `checkAddonUrlAndHash.js` and then adding that to the PR body generated in `workflows/validateAllAddons.yml`.

2024-09-10 09:02 UTC, seanbudd commented
@SaschaCowley - this is now ready for review

2024-09-10 09:04 UTC, seanbudd commented on .github/workflows/checkAddonUrlAndHash.js
good call - I've made this a lot more readable

2024-09-11 01:32 UTC, SaschaCowley approved these changes
This looks good to me!

2024-09-11 01:32 UTC, SaschaCowley commented on .github/workflows/checkAddonUrlAndHash.js
> +  const metadataFileNormalised = metadataFile.replace(/\\/g, '/');
Slightly more self-documenting
```suggestion
  const metadataFileNormalised = metadataFile.replaceAll('\\', '/');
```

2024-09-15 23:22 UTC, seanbudd commented on .github/workflows/checkAddonUrlAndHash.js
> +    const strippedStderr = stderr.replace("\n", "  ").replace("\r", "");
```suggestion
    const strippedStderr = stderr.replaceAll("\n", "  ").replaceAll("\r", "");
```

2024-09-15 23:24 UTC, merged